/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Shipping;

import Repository.MongoDBConnection;
import UI.MainJFrame;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.UpdateOptions;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.conversions.Bson;
import org.bson.types.ObjectId;

/**
 *
 * @author Shari
 */
public class ShippingCoordinatorDashboard extends javax.swing.JPanel {

    MainJFrame mainpage;

    /**
     * Creates new form ShippingProviderDashboard
     */
    public ShippingCoordinatorDashboard(MainJFrame mainpage) {
        initComponents();
        this.mainpage = mainpage;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Shipping Coordinator Dashboard");

        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "From", "To", "Shipping Method", "Status", "Co2 Emission"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(607, 607, 607)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        mainpage.role = null;
        mainpage.dispose();
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MongoDatabase db = MongoDBConnection.getDatabase();
        MongoCollection<Document> shippingHistoryCollection = db.getCollection("shippingHistory");
        MongoCollection<Document> ordersCollection = db.getCollection("orders");

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String orderId = model.getValueAt(i, 0).toString();
            String shippingMethod = model.getValueAt(i, 3).toString();
            String status = model.getValueAt(i, 4).toString();
            Object co2Value = model.getValueAt(i, 5);
            double co2Emission = 0.0;

            try {
                if (co2Value != null && !co2Value.toString().trim().isEmpty()) {
                    co2Emission = Double.parseDouble(co2Value.toString().trim());
                } else {
                    // Skip saving this row if co2 is blank
                    continue;
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Invalid CO2 emission at row " + (i + 1));
                return;
            }

            Document filter = new Document("_id", new ObjectId(orderId));  // Use correct identifier
            Document update = new Document("$set", new Document("status", status));

            ordersCollection.updateOne(filter, update, new UpdateOptions().upsert(true));

            Document historyDoc = new Document("order_id", orderId)
                    .append("shipping_method", shippingMethod)
                    .append("status", status)
                    .append("co2_emission", co2Emission);

            // Insert or update based on order_id
            shippingHistoryCollection.updateOne(
                    new Document("order_id", orderId),
                    new Document("$set", historyDoc),
                    new com.mongodb.client.model.UpdateOptions().upsert(true)
            );

        }

        javax.swing.JOptionPane.showMessageDialog(this, "✅ Shipping history updated successfully!");
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        MongoDatabase db = MongoDBConnection.getDatabase();
        MongoCollection<Document> ordersCollection = db.getCollection("orders");
        MongoCollection<Document> shippingHistoryCollection = db.getCollection("shippingHistory");

        for (Document doc : ordersCollection.find()) {
            Document historyDoc = shippingHistoryCollection.find(new Document("order_id", doc.getObjectId("_id").toHexString())).first();
            String shippingMethod = (historyDoc != null && historyDoc.getString("shipping_method") != null)
                    ? historyDoc.getString("shipping_method")
                    : "Select Mode";
            String co2 = (historyDoc != null && historyDoc.get("co2_emission") != null)
                    ? String.valueOf(historyDoc.get("co2_emission"))
                    : "";
            model.addRow(new Object[]{
                doc.getObjectId("_id").toHexString(),
                "Boston", // Static value
                doc.getString("delivery_address"),
                shippingMethod,
                doc.getString("status") != null ? doc.getString("status") : "Pending",
                co2
            });
        }

        JComboBox<String> statusCombo = new JComboBox<>(new String[]{"Pending", "Shipped", "Delivered"});
        jTable1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(statusCombo));

        JComboBox<String> shippingCombo = new JComboBox<>(new String[]{"Air", "Ground", "Sea"});
        jTable1.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(shippingCombo));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
