/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Auditor;

import Repository.MongoDBConnection;
import Service.ButtonRenderer;
import Service.ReviewButtonEditor;
import UI.MainJFrame;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import org.bson.Document;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import java.awt.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Shari
 */
public class AuditorDashboard extends javax.swing.JPanel {

    MainJFrame mainpage;
    String roleId = null;

    /**
     * Creates new form AuditorDashboard
     */
    public AuditorDashboard(MainJFrame mainpage) {
        initComponents();
        this.mainpage = mainpage;
        this.roleId = mainpage.roleId;
        setLayout(new BorderLayout(10, 10));
        setBackground(new Color(240, 255, 255)); // Neon light bluish background

        // Title
        JLabel lblTitle = new JLabel("Audit Dashboard", SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblTitle.setForeground(new Color(0, 153, 153)); // Neon cyan

        JButton btnLogout = new JButton("Logout");
        btnLogout.setBackground(new Color(0, 153, 153));
        btnLogout.setForeground(Color.WHITE);
        btnLogout.setFocusPainted(false);
        btnLogout.setBorder(BorderFactory.createEmptyBorder(10, 30, 10, 30));
        btnLogout.addActionListener(e -> {
            mainpage.role = null;
            mainpage.dispose();
            new MainJFrame().setVisible(true);
        });

        JPanel titlePanel = new JPanel(new BorderLayout());
        titlePanel.setBackground(getBackground());
        titlePanel.setBorder(new EmptyBorder(10, 20, 0, 20));
        titlePanel.add(lblTitle, BorderLayout.CENTER);
        titlePanel.add(btnLogout, BorderLayout.WEST);
        
        // Subtitle
        JLabel lblSubtitle = new JLabel("Review & Score Product", SwingConstants.CENTER);
        lblSubtitle.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblSubtitle.setForeground(new Color(0, 102, 102));   

         JPanel subtitlePanel = new JPanel(new BorderLayout());
        subtitlePanel.setBackground(getBackground());
        subtitlePanel.add(lblSubtitle, BorderLayout.CENTER);
        subtitlePanel.setBorder(new EmptyBorder(0, 0, 10, 0));

        // Table
        viewEditTbl = new JTable(new DefaultTableModel(new Object[][]{}, new String[]{
            "Product ID", "Name", "Description", "Material Used", "Co2 Emission", "Eco Score", "Actions"
        }));
        styleTable(viewEditTbl);

        JScrollPane scrollPane = new JScrollPane(viewEditTbl);
        scrollPane.setBorder(new EmptyBorder(0, 20, 20, 20));

        JPanel northPanel = new JPanel(new BorderLayout());
        northPanel.setBackground(getBackground());
        northPanel.add(titlePanel, BorderLayout.NORTH);
        northPanel.add(subtitlePanel, BorderLayout.SOUTH);

        add(northPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);

        setupTable();
        populateTable();
    }

    private void styleTable(JTable table) {
        JTableHeader header = table.getTableHeader();
        header.setBackground(new Color(204, 255, 255));
        header.setForeground(new Color(0, 102, 102));
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));

        table.setRowHeight(25);
        table.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        table.setGridColor(new Color(180, 238, 238));
        table.setSelectionBackground(new Color(204, 255, 255));

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            final Color evenRow = new Color(235, 255, 255);
            final Color oddRow = Color.WHITE;

            public Component getTableCellRendererComponent(JTable tbl, Object val, boolean sel, boolean foc, int row, int col) {
                Component c = super.getTableCellRendererComponent(tbl, val, sel, foc, row, col);
                c.setBackground(!sel ? (row % 2 == 0 ? evenRow : oddRow) : new Color(204, 255, 255));
                return c;
            }
        };

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setupTable() {
        viewEditTbl.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Product ID", "Name", "Description", "Material Used", "Co2 Emission", "Eco Score", "Actions"}
        ));
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) viewEditTbl.getModel();
        model.setRowCount(0);

        MongoDatabase db = MongoDBConnection.getDatabase();
        MongoCollection<Document> productCollection = db.getCollection("products");

        for (Document doc :  productCollection.find(
        Filters.and(
            Filters.eq("is_audit", true),
            Filters.eq("ecoscore", 0)))) {
            model.addRow(new Object[]{
                doc.getString("product_id"),
                doc.getString("product_name"),
                doc.getString("description"),
                doc.getString("materials_used"),
                doc.getInteger("carbon_score"),
                doc.getInteger("ecoscore"),
                "Review"
            });
        }

        TableColumn actionColumn = viewEditTbl.getColumn("Actions");
        actionColumn.setCellRenderer(new ButtonRenderer());
        actionColumn.setCellEditor(new ReviewButtonEditor(new JCheckBox(), viewEditTbl, this));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitleReview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewEditTbl = new javax.swing.JTable();
        LogoutBTN = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Audit Dashboard");

        lblTitleReview.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleReview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleReview.setText("Review &  Score Product ");

        viewEditTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Description", "Material Used", "Co2 Emission", "Eco Score", "Actions"
            }
        ));
        viewEditTbl.setToolTipText("");
        jScrollPane1.setViewportView(viewEditTbl);

        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(lblTitleReview, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitleReview, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        mainpage.role = null;
        mainpage.dispose();
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_LogoutBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleReview;
    private javax.swing.JTable viewEditTbl;
    // End of variables declaration//GEN-END:variables
}
