/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.Admin.ManageUsers;
import UI.ShippingCoordinator.ShippingCoordinatorDashboard;
import UI.ProdAuditor.ProductAuditorDashboard;
import UI.Buyer.BuyerSplitPage;
import UI.Seller.SellerSplitPage;
import Repository.MongoDBConnection;
import Repository.SchemaCreator;
import UI.Auditor.AuditorDashboard;
import UI.Customersupport.SupportPage;
import UI.Accountant.SellerAccountant;
import UI.Accountant.ShippingAccountantDashboard;
import UI.Admin.AdminSplitPage;
import com.mongodb.client.MongoCollection;

import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import org.bson.Document;

/**
 *
 * @author Shari
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public String currentUsername = null;
    public String role = null;
    public String roleId = null;
    public String enterpriseName = null;
    public String organizationName = null;
    public String userId = null;

    public MainJFrame() {
        initComponents();
        setTitle("EcoCart Login");
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize window
        setLocationRelativeTo(null);
        setResizable(true);

        // Left background image covering half screen
        Mainpic.setIcon(new ImageIcon(getClass().getResource("/Images/Mainframe2.png")));
        Mainpic.setHorizontalAlignment(SwingConstants.CENTER);
        Mainpic.setVerticalAlignment(SwingConstants.CENTER);

        // Right panel styling
        rightpanel.setBackground(new Color(255,255,255 ));
        rightpanel.setLayout(null); // Absolute positioning

        // EcoCart Logo
        ImgLogo.setIcon(new ImageIcon(getClass().getResource("/Images/logo.png")));
        ImgLogo.setBounds(320, 70, 100, 50); // adjust size as needed
        rightpanel.add(ImgLogo);

        // "EcoCart" title
        lblTitle.setText("EcoCart");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblTitle.setBounds(360, 80, 100, 30);
        rightpanel.add(lblTitle);

        // Login heading
        lbllogin.setText("Log In");
        lbllogin.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lbllogin.setBounds(370, 130, 100, 30);
        rightpanel.add(lbllogin);

        // Username
        lblUsername.setText("Username");
        lblUsername.setBounds(250, 200, 100, 25);
        txtUsername.setBounds(250, 225, 300, 35);
        rightpanel.add(lblUsername);
        rightpanel.add(txtUsername);

        // Password
        lblPassword.setText("Password");
        lblPassword.setBounds(250, 275, 100, 25);
        txtPassword.setBounds(250, 300, 300, 35);
        rightpanel.add(lblPassword);
        rightpanel.add(txtPassword);

        // Login button
        loginBTN.setText("Log In");
        loginBTN.setBounds(250, 350, 300, 40);
        loginBTN.setBackground(new Color(100, 150, 200));
        loginBTN.setForeground(Color.WHITE);
        loginBTN.setFont(new Font("Segoe UI", Font.BOLD, 14));
        loginBTN.setFocusPainted(false);
        rightpanel.add(loginBTN);

        // Sign up button
        signupBTN.setText("Sign Up");
        signupBTN.setBounds(250, 400, 300, 40);
        signupBTN.setBackground(Color.LIGHT_GRAY);
        signupBTN.setFont(new Font("Segoe UI", Font.BOLD, 14));
        signupBTN.setFocusPainted(false);
        rightpanel.add(signupBTN);
        
        SplitPane.setDividerSize(0);
        SplitPane.setBorder(BorderFactory.createEmptyBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        leftpanel = new javax.swing.JPanel();
        Mainpic = new javax.swing.JLabel();
        rightpanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        signupBTN = new javax.swing.JButton();
        ImgLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setMaximumSize(new java.awt.Dimension(1500, 800));
        SplitPane.setPreferredSize(new java.awt.Dimension(1500, 800));

        leftpanel.setMaximumSize(new java.awt.Dimension(700, 400));
        leftpanel.setPreferredSize(new java.awt.Dimension(600, 600));

        Mainpic.setBackground(new java.awt.Color(255, 255, 255));
        Mainpic.setForeground(new java.awt.Color(255, 255, 255));
        Mainpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mainframe2.png"))); // NOI18N
        Mainpic.setPreferredSize(new java.awt.Dimension(600, 1100));

        javax.swing.GroupLayout leftpanelLayout = new javax.swing.GroupLayout(leftpanel);
        leftpanel.setLayout(leftpanelLayout);
        leftpanelLayout.setHorizontalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpic, javax.swing.GroupLayout.PREFERRED_SIZE, 757, Short.MAX_VALUE)
        );
        leftpanelLayout.setVerticalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Mainpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        SplitPane.setLeftComponent(leftpanel);

        rightpanel.setBackground(new java.awt.Color(255, 255, 255));
        rightpanel.setMaximumSize(new java.awt.Dimension(1500, 800));
        rightpanel.setPreferredSize(new java.awt.Dimension(600, 600));

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        loginBTN.setText("Login");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        signupBTN.setText("Sign up");
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });

        ImgLogo.setBackground(new java.awt.Color(255, 255, 255));
        ImgLogo.setForeground(new java.awt.Color(255, 255, 255));
        ImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        lblTitle.setForeground(new java.awt.Color(0, 51, 51));

        lbllogin.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout rightpanelLayout = new javax.swing.GroupLayout(rightpanel);
        rightpanel.setLayout(rightpanelLayout);
        rightpanelLayout.setHorizontalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightpanelLayout.createSequentialGroup()
                        .addComponent(signupBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightpanelLayout.createSequentialGroup()
                        .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightpanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rightpanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(ImgLogo)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightpanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbllogin)))
                .addContainerGap())
        );
        rightpanelLayout.setVerticalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImgLogo)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbllogin)
                .addGap(35, 35, 35)
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(loginBTN)
                .addGap(18, 18, 18)
                .addComponent(signupBTN)
                .addContainerGap())
        );

        SplitPane.setRightComponent(rightpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        //SchemaCreator.createSchema();
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        MongoDatabase db = MongoDBConnection.getDatabase();
        if (db != null) {
            MongoCollection<Document> userCollection = db.getCollection("users");
            MongoCollection<Document> roleCollection = db.getCollection("roles");
            MongoCollection<Document> organizationCollection = db.getCollection("organizations");
            MongoCollection<Document> enterpriseCollection = db.getCollection("enterprises");

            Document query = new Document("username", username).append("password", password);
            Document user = userCollection.find(query).first();

            if (user != null) {
                currentUsername = username;

                // Fetch role_id from user
                roleId = user.getString("role_id");
                userId = user.getString("user_id");

                // Fetch role details
                Document roleQuery = new Document("role_id", roleId);
                Document roleDoc = roleCollection.find(roleQuery).first();
                if (roleDoc != null) {
                    role = roleDoc.getString("role_name");
                }

                // Fetch organization details (OPTIONAL if you linked role -> organization in MongoDB)
                Document orgQuery = new Document("role_id", roleId);
                Document orgDoc = organizationCollection.find(orgQuery).first();
                if (orgDoc != null) {
                    organizationName = orgDoc.getString("organization_name");

                    // Fetch enterprise details
                    String enterpriseId = orgDoc.getString("enterprise_id");
                    Document entQuery = new Document("enterprise_id", enterpriseId);
                    Document entDoc = enterpriseCollection.find(entQuery).first();
                    if (entDoc != null) {
                        enterpriseName = entDoc.getString("enterprise_name");
                    }
                }

                System.out.println("Login successful:");
                System.out.println("User: " + currentUsername);
                System.out.println("Role: " + role);
                System.out.println("Organization: " + organizationName);
                System.out.println("Enterprise: " + enterpriseName);

                // Redirect based on role
                switch (role.toLowerCase()) {
                    case "buyer":
                        BuyerSplitPage buyerPanel = new BuyerSplitPage(this, userId);
                        this.setContentPane(buyerPanel);
                        break;

                    case "seller":
                        SellerSplitPage sellerPanel = new SellerSplitPage(this);
                        this.setContentPane(sellerPanel);
                        break;

                    case "auditor":
                        AuditorDashboard auditorPanel = new AuditorDashboard(this);
                        this.setContentPane(auditorPanel);
                        break;

                    case "prdauditor":
                        ProductAuditorDashboard certifierPanel = new ProductAuditorDashboard(this);
                        this.setContentPane(certifierPanel);
                        break;

                    case "shipping coordinator":
                        ShippingCoordinatorDashboard shippingPanel = new ShippingCoordinatorDashboard(this);
                        this.setContentPane(shippingPanel);
                        break;

                    case "shipping accounts":
                        ShippingAccountantDashboard shippingManager = new ShippingAccountantDashboard(this);
                        this.setContentPane(shippingManager);
                        break;

                    case "seller accountant":
                        SellerAccountant sellerAccountant = new SellerAccountant(this);
                        this.setContentPane(sellerAccountant);
                        break;

                    case "support specialist":
                        SupportPage support_spe = new SupportPage(this, userId);
                        this.setContentPane(support_spe);
                        break;

                    case "admin":
                        AdminSplitPage adminPanel = new AdminSplitPage(this);
                        this.setContentPane(adminPanel);
                        break;

                    default:
                        JOptionPane.showMessageDialog(this, "❗ Unknown role detected: " + role);
                        break;
                }

                this.invalidate();
                this.validate();

            } else {
                System.out.println("Invalid credentials. Try again!");
                JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
            }
        } else {
            System.out.println("Database connection failed!");
            JOptionPane.showMessageDialog(this, "Database Connection Failed. Please try later.");
        }
    }//GEN-LAST:event_loginBTNActionPerformed

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBTNActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new SignUp(this));  // Pass current MainJFrame reference
        this.invalidate();
        this.validate();

    }//GEN-LAST:event_signupBTNActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLogo;
    private javax.swing.JLabel Mainpic;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JButton loginBTN;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JButton signupBTN;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
