/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Buyer;

import UI.MainJFrame;
import UI.Seller.UploadProduct;
import UI.Seller.ViewProduct;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author Shari
 */
public class BuyerSplitPage extends javax.swing.JPanel {

    private MainJFrame mainpage;
    private String userId;

    public BuyerSplitPage(MainJFrame mainpage, String userId) {
        this.mainpage = mainpage;
        this.userId = userId;
        initComponents();

        //  Styling 
        Color darkGreen = new Color(0, 77, 64);
        Color hoverGreen = new Color(38, 166, 91);
        Font buttonFont = new Font("Segoe UI", Font.BOLD, 14);

        leftpanel.setBackground(darkGreen);

        JButton[] buttons = {btnProducts, btnOrders, raiseComplain, LogoutBTN};
        for (JButton btn : buttons) {
            btn.setBackground(darkGreen);
            btn.setForeground(Color.WHITE);
            btn.setFont(buttonFont);
            btn.setFocusPainted(false);
            btn.setBorder(BorderFactory.createLineBorder(darkGreen.darker()));
        }

        rightpanel.setLayout(new BorderLayout());
        rightpanel.setBackground(Color.WHITE);

// Remove old layout components from rightpanel
        rightpanel.removeAll();

// Add the title to the top
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblTitle.setForeground(new Color(0, 77, 64));
        rightpanel.add(lblTitle, BorderLayout.NORTH);

// Center the image
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        rightpanel.add(jLabel1, BorderLayout.CENTER);

        SplitPane.setDividerSize(0);
        SplitPane.setBorder(BorderFactory.createEmptyBorder());
    }

    private void setupButtonHoverEffect(JButton button) {
        Color originalBg = new Color(0, 77, 64);  // Soft leafy green #A8D5BA
        Color originalFg = Color.WHITE;

        Color hoverBg = new Color(38, 166, 91);     // Lighter mint #D1EFE0
        Color hoverFg = Color.WHITE;

        Border originalBorder = BorderFactory.createLineBorder(originalBg.darker());
        Border hoverBorder = BorderFactory.createLineBorder(hoverBg.darker());

        button.setBackground(originalBg);
        button.setForeground(originalFg);
        button.setBorder(originalBorder);
        button.setFocusPainted(false);

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverBg);
                button.setForeground(hoverFg);
                button.setBorder(hoverBorder);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(originalBg);
                button.setForeground(originalFg);
                button.setBorder(originalBorder);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        leftpanel = new javax.swing.JPanel();
        btnProducts = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        raiseComplain = new javax.swing.JButton();
        LogoutBTN = new javax.swing.JButton();
        rightpanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(120000000, 120000000));
        setPreferredSize(new java.awt.Dimension(2000, 1100));

        SplitPane.setPreferredSize(new java.awt.Dimension(2000, 800));

        leftpanel.setPreferredSize(new java.awt.Dimension(250, 800));

        btnProducts.setText("Products");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });

        btnOrders.setText("Order History");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        raiseComplain.setText("Raise a Issue");
        raiseComplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseComplainActionPerformed(evt);
            }
        });

        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftpanelLayout = new javax.swing.GroupLayout(leftpanel);
        leftpanel.setLayout(leftpanelLayout);
        leftpanelLayout.setHorizontalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raiseComplain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        leftpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LogoutBTN, btnOrders, btnProducts, raiseComplain});

        leftpanelLayout.setVerticalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnProducts)
                .addGap(26, 26, 26)
                .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(raiseComplain)
                .addGap(190, 190, 190)
                .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        leftpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LogoutBTN, btnOrders, btnProducts, raiseComplain});

        SplitPane.setLeftComponent(leftpanel);

        rightpanel.setPreferredSize(new java.awt.Dimension(2000, 800));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Buyer Dashboard");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Environmenta.png"))); // NOI18N
        jLabel1.setPreferredSize(null);

        javax.swing.GroupLayout rightpanelLayout = new javax.swing.GroupLayout(rightpanel);
        rightpanel.setLayout(rightpanelLayout);
        rightpanelLayout.setHorizontalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightpanelLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightpanelLayout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rightpanelLayout.setVerticalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SplitPane.setRightComponent(rightpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 2000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        // TODO add your handling code here:
        Products ps = new Products(mainpage, userId);
        SplitPane.setRightComponent(ps);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        // TODO add your handling code here:
        Orders or = new Orders(mainpage, userId);
        SplitPane.setRightComponent(or);
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void raiseComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseComplainActionPerformed
        // TODO add your handling code here:
        RaiseIssue rs = new RaiseIssue(mainpage, userId);
        SplitPane.setRightComponent(rs);
    }//GEN-LAST:event_raiseComplainActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        mainpage.role = null;
        mainpage.dispose();
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_LogoutBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JButton raiseComplain;
    private javax.swing.JPanel rightpanel;
    // End of variables declaration//GEN-END:variables
}
